name: 'GCS deploy in prod environment'

on:
  push:
    branches:
      - master
    paths:
      - "terraform/prod/**"

jobs:
  terraform:
    name: Terraform GCS Bucket deployment for dev environment
    runs-on: ubuntu-latest
    container: jeanflores2c93/terraform-gcp-sdk-agent
    defaults:
      run:
        working-directory: terraform/prod/
    steps:
      - name: Checkout
        if: ${{ github.event.pull_request.merged }}
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        if: ${{ github.event.pull_request.merged }}
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Format
        if: ${{ github.event.pull_request.merged }}
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        if: ${{ github.event.pull_request.merged }}
        id: init
        run: terraform init

      - name: Terraform Validate
        if: ${{ github.event.pull_request.merged }}
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: ${{ github.event.pull_request.merged }}
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve



